// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVPAJK6vE3N8De-_ai9OW-xrXGv1u4mXs',
    appId: '1:834600155327:android:ff25e22611d220ab086e0a',
    messagingSenderId: '834600155327',
    projectId: 'flash-chat-e0f64',
    storageBucket: 'flash-chat-e0f64.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxHD3VgeceWqB08cmiQBosJf520x9ri70',
    appId: '1:834600155327:ios:0a532095c3ea8aec086e0a',
    messagingSenderId: '834600155327',
    projectId: 'flash-chat-e0f64',
    storageBucket: 'flash-chat-e0f64.appspot.com',
    iosClientId:
        '834600155327-qv3eoj2b5u5t2l61ejq2umqs6204mdb6.apps.googleusercontent.com',
    iosBundleId: 'co.appbrewery.flashChat',
  );
}
